#!/bin/ksh
#
# dwmail - download my mail and inform me
# author: haesbaert
#
# usage: dwmail

Script=${0##*/}

# Check for notify-send binary
if ! which notify-send > /dev/null
then
	echo "Could not find notify-send binary"
	echo "ubuntu package is libnotify-bin"
	exit 1
fi

while true
do
	Line=$(getmail | tail -n 1)
	Newmail=$(echo "$Line" | cut -d ' ' -f 2)
	echo 
	Bytes=$(echo "$Line" | cut -d ' ' -f 5 | sed 's/(//g')
	if [ $Newmail -gt 0 ]
	then
		notify-send -t 10000 "You have $Newmail new messages ($Bytes bytes)"
	fi

	sleep 300
done
