#!/bin/ksh
#
# wifi - Connect to wifi spots in OpenBSD.
#
# usage: wifi [-n] nwid
#        wifi [-n] -w wpakey nwid
#        wifi -r
#set -x
Script=${0##*/}

Nflag=false
Resetflag=false
Wpaflag=false
Interface=""

# we must be root
if test $(whoami) != root; then
	sudo $0 $@
	exit $?
fi

function usage
{
    echo "usage: $Script [-r] [-w wpakey] nwid
	    -h : this help message
	    -i : specify the interface
            -n : don't try dhcp
            -r : reset the interface
	    -w : specify the wpa2 key"
    exit 1
}

while getopts rw: Opt
do
	case "$Opt" in
		i) Interface="$OPTARG";;
		n) Nflag=true;;
		r) Resetflag=true;;
		w) Wpaflag="$OPTARG";;
		\?) usage;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 0 -a ! $Resetflag ]
then
	usage
fi

Nwid="$1"

if [ -z "$Interface" ]
then
	Interface=`ifconfig wlan 2>/dev/null | (IFS=: read INT REST; echo $INT)`
fi

if $Resetflag
then
	ifconfig "$Interface" -bssid -chan media autoselect \
                -nwid -nwkey -wpa -wpapsk
	exit 0
fi

if [ $Wpaflag != false ]
then
	ifconfig "$Interface" nwid "$Nwid" wpa wpapsk "$Wpaflag"
else
	ifconfig "$Interface" nwid "$Nwid"
fi

if ! $Nflag
then
	dhclient "$Interface"
fi

exit $?
